"""Montesinos knots K(p1/q1; ...; pk/qk) by tangle calculus with Racah matrices.

The knot is the numerator closure of the sum T_1 + ... + T_k of rational
tangles.  Each rational tangle is built from the 0 or ∞ tangle by twists of the
right pair (H) and of the bottom pair (V); the orientation of every endpoint at
every step is tracked (``_orientations``).  A 4-point tangle is a coordinate
vector in one of two channel bases:

    H basis: fuse the left pair (a,d) and the right pair (b,c)
    V basis: fuse the top pair (a,b) and the bottom pair (d,c)

and each pair is parallel (R⊗R, channels Q) or antiparallel (R⊗R̄, channels X).
Per orientation pattern (H type, V type):

    (anti, anti):  c_H = S̄ v_V
    (par,  anti):  c_H = V v_V        (V = S^-1 of the family-P data)
    (anti, par ):  c_H = S v_V

Twists are diagonal: parallel pairs T^e, antiparallel pairs T̄^e with
exponents  H-anti: +s,  H-par: -s,  V-anti: +s,  V-par: -s  times the relative
handedness GROUP = -1 of the (H-anti, V-par) group (pinned on the fundamental
representation against KnotInfo for all 721 Montesinos knots <= 12 crossings).

Tangle sum = block product C_1 E^-1 C_2 E^-1 ... in the H basis of the vertex
channel type, where E are the coordinates of the 0-tangle in the *plain*
pattern of that type (antiparallel 'ioio' -> S̄ e0, parallel 'iooi' -> V e0);
the closure is  sum_X d_X Tr(C E^-1 ...).  This is gauge covariant: no Gram
matrices are needed.  Channel dimensions are recovered gauge-invariantly,
d_X = S̄_0X S̄_X0 d_R^2 and d_Q = S_0Q V_Q0 d_R^2 (multiplicity-free data).

Data: data/racah/montesinos/{P,H,G}_<R>.json.gz (scripts/import_racah_montesinos.py):
family P for rectangular R, family H (Hecke Y-gauge) and family G (mixed S only;
[2,1,1] and the non-rectangular five-box reps generated by
scripts/make_mixed_S_gtpath.sh), together all 29 R with |R| <= 6.
"""
from __future__ import annotations

import gzip
import json
import os
import random
from fractions import Fraction
from functools import lru_cache

from ..algebra.fields import BadPoint, GF
from ..knots.families import MontesinosKnot
from ..reps.partitions import P, conjugate
from ..reps.qdim import qdim
from .base import Method

DATA_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", "..",
                                         "data", "racah", "montesinos"))
GROUP = -1


# ---------------------------------------------------------------------------
# rational tangles and orientations
# ---------------------------------------------------------------------------

def _ops_for(fr):
    x = Fraction(fr)
    ops = []
    while True:
        if x == 0:
            return "0", ops[::-1]
        if abs(x) >= 1:
            s = 1 if x > 0 else -1
            ops.append(("H", s))
            x -= s
        else:
            y = 1 / x
            s = 1 if y > 0 else -1
            ops.append(("V", s))
            y -= s
            if y == 0:
                return "inf", ops[::-1]
            x = 1 / y


def _build(fr):
    base, ops = _ops_for(fr)
    st = ({"a": (0, 0), "b": (0, 1), "d": (1, 0), "c": (1, 1)} if base == "0" else
          {"a": (0, 0), "d": (0, 1), "b": (1, 0), "c": (1, 1)})
    hist = [dict(st)]
    for kind, _ in ops:
        x, y = ("b", "c") if kind == "H" else ("c", "d")
        st[x], st[y] = st[y], st[x]
        hist.append(dict(st))
    return base, ops, hist


@lru_cache(maxsize=None)
def _orientations(fracs):
    """(components, [(base, ops, [orientation per step])]) for N(T_1 + ... + T_k)."""
    T = [_build(f) for f in fracs]
    k = len(T)
    ext = {}
    for i in range(k - 1):
        ext[(i, "b")], ext[(i + 1, "a")] = (i + 1, "a"), (i, "b")
        ext[(i, "c")], ext[(i + 1, "d")] = (i + 1, "d"), (i, "c")
    ext[(0, "a")], ext[(k - 1, "b")] = (k - 1, "b"), (0, "a")
    ext[(0, "d")], ext[(k - 1, "c")] = (k - 1, "c"), (0, "d")
    inner = []
    for _, _, hist in T:
        st = hist[-1]
        inner.append({e1: e2 for e1 in st for e2 in st if e1 != e2 and st[e1][0] == st[e2][0]})
    orient, seen, comps = {}, set(), 0
    for s0 in [(i, e) for i in range(k) for e in "abcd"]:
        if s0 in seen:
            continue
        comps += 1
        cur = s0
        while cur not in seen:
            i, e = cur
            seen.add(cur)
            orient[cur] = 1              # in
            e2 = inner[i][e]
            seen.add((i, e2))
            orient[(i, e2)] = 0          # out
            cur = ext[(i, e2)]
    out = []
    for i, (base, ops, hist) in enumerate(T):
        endo = {hist[-1][e]: orient[(i, e)] for e in "abcd"}
        steps = [{e: endo[st[e]] for e in "abcd"} for st in hist]
        out.append((base, tuple(ops), steps))
    return comps, out


def _types(o):
    return ("par" if o["a"] == o["d"] else "anti", "par" if o["a"] == o["b"] else "anti")


# ---------------------------------------------------------------------------
# data
# ---------------------------------------------------------------------------

class _Poly:
    __slots__ = ("terms",)

    def __init__(self, terms):
        self.terms = [tuple(t) for t in terms]

    def ev(self, F, A, q, cache):
        s = F.zero
        for i, j, c in self.terms:
            k = (i, j)
            if k not in cache:
                cache[k] = A ** i * q ** j
            s = s + cache[k] * c
        return s


class _Flat:
    """Matrix of rational entries num/den for vectorised evaluation mod p."""

    def __init__(self, mat):
        self.shape = (len(mat), len(mat[0]))
        self.parts = []
        for which in (0, 1):
            coef, ai, qj, ptr = [], [], [], []
            for row in mat:
                for e in row:
                    ptr.append(len(coef))
                    terms = e[which].terms or [(0, 0, 0)]
                    for i, j, c in terms:
                        ai.append(i)
                        qj.append(j)
                        coef.append(c)
            self.parts.append((coef, ai, qj, ptr))
        self._np = None
        self._coef = {}
        self._row = {}

    def _prepare(self):
        """Static grouping of the terms by (entry, A-exponent), so that for a
        fixed q (interpolation evaluates whole rows of A-points at one q) every
        entry collapses to a short polynomial in A."""
        import numpy as np
        self._np = []
        for coef, ai, qj, ptr in self.parts:
            ai, qj, ptr = np.array(ai), np.array(qj), np.array(ptr)
            entry = np.repeat(np.arange(len(ptr)), np.diff(np.append(ptr, len(ai))))
            key = entry * (int(ai.max()) - int(ai.min()) + 1) + (ai - ai.min())
            order = np.argsort(key, kind="stable")
            ks = key[order]
            starts = np.flatnonzero(np.r_[True, ks[1:] != ks[:-1]])
            g_entry, g_ai = entry[order][starts], ai[order][starts]
            g_ptr = np.flatnonzero(np.r_[True, g_entry[1:] != g_entry[:-1]])
            self._np.append((ai, qj, ptr, order, starts, g_ai, g_ptr))

    def evaluate(self, p, pw, q=None):
        import numpy as np
        if self._np is None:
            self._prepare()
        vals = []
        for which in (0, 1):
            key = (which, p)
            if key not in self._coef:
                self._coef[key] = np.array([int(c) % p for c in self.parts[which][0]], dtype=np.int64)
            ai, qj, ptr, order, starts, g_ai, g_ptr = self._np[which]
            if q is None:
                t = self._coef[key] * pw("A", ai) % p * pw("q", qj) % p
                vals.append(np.add.reduceat(t, ptr) % p)
                continue
            ck = (which, p, q)
            if self._row.get(which, (None,))[0] != ck:
                t = (self._coef[key] * pw("q", qj) % p)[order]
                self._row[which] = (ck, np.add.reduceat(t, starts) % p)
            t = self._row[which][1] * pw("A", g_ai) % p
            vals.append(np.add.reduceat(t, g_ptr) % p)
        num, den = vals
        if (den == 0).any():
            raise BadPoint("pole in Racah data")
        return (num * _inv_vec(den, p) % p).reshape(self.shape)


def _inv_vec(x, p):
    """Elementwise inverse mod p < 2^31 (Fermat, vectorised)."""
    import numpy as np
    out = np.ones_like(x)
    b, e = x % p, p - 2
    while e:
        if e & 1:
            out = out * b % p
        b = b * b % p
        e >>= 1
    return out


def _powers(p, A, q):
    """pw(var, exponents array) -> A^e or q^e mod p, from a cached table."""
    import numpy as np
    tabs = {}

    def pw(var, e):
        x = A if var == "A" else q
        lo, hi = int(e.min()), int(e.max())
        if var not in tabs or tabs[var][0] > lo or tabs[var][1] < hi:
            xi = pow(x, -1, p)
            tab = [pow(xi, -k, p) if k < 0 else pow(x, k, p) for k in range(lo, hi + 1)]
            tabs[var] = (lo, hi, np.array(tab, dtype=np.int64))
        lo0, _, tab = tabs[var]
        return tab[e - lo0]
    return pw


class PData:
    """Family P, multiplicity-free R: S̄, S, V, T, T̄."""

    def __init__(self, R, root=DATA_DIR):
        with gzip.open(os.path.join(root, "P_%s.json.gz" % "".join(map(str, R))), "rt") as f:
            d = json.load(f)
        self.R = tuple(R)
        self.vac = d["vacuum_index"]
        self.mats = {k: [[(_Poly(n), _Poly(dd)) for n, dd in row] for row in d[k]]
                     for k in ("Sbar", "S", "V")}
        self.diags = {k: [(_Poly(n), _Poly(dd)) for n, dd in d[k]] for k in ("T", "Tbar")}
        self.n = len(d["Sbar"])
        self.flat = {k: _Flat(M) for k, M in self.mats.items()}
        self.flat.update({k: _Flat([v]) for k, v in self.diags.items()})

    def evaluate_np(self, p, A, q):
        import numpy as np
        pw = _powers(p, A, q)
        out = {k: f.evaluate(p, pw, q) for k, f in self.flat.items()}
        out["T"], out["Tbar"] = out["T"][0], out["Tbar"][0]
        F = GF(p)
        dR = int(qdim(self.R, F(A), F(q)))
        Sb, S, V, z = out["Sbar"], out["S"], out["V"], self.vac
        out["d_anti"] = Sb[z, :] * Sb[:, z] % p * (dR * dR % p) % p
        out["d_par"] = S[z, :] * V[:, z] % p * (dR * dR % p) % p
        out["dR"] = dR
        out["blocks_anti"] = [[[X]] for X in range(self.n)]
        out["blocks_par"] = [[[Qi]] for Qi in range(self.n)]
        out["vac"] = z
        return {k: (np.asarray(v, dtype=np.int64) if k in ("d_anti", "d_par") else v)
                for k, v in out.items()}

    def evaluate(self, F, A, q):
        cache = {}

        def ev(e):
            den = e[1].ev(F, A, q, cache)
            if den == 0:
                raise BadPoint("pole in Racah data")
            return e[0].ev(F, A, q, cache) / den
        out = {k: [[ev(e) for e in row] for row in M] for k, M in self.mats.items()}
        out.update({k: [ev(e) for e in v] for k, v in self.diags.items()})
        dR = qdim(self.R, A, q)
        Sb, S, V = out["Sbar"], out["S"], out["V"]
        z = self.vac
        out["d_anti"] = [Sb[z][X] * Sb[X][z] * dR * dR for X in range(self.n)]
        out["d_par"] = [S[z][Qi] * V[Qi][z] * dR * dR for Qi in range(self.n)]
        out["dR"] = dR
        out["blocks_anti"] = [[[X]] for X in range(self.n)]     # 1x1 blocks
        out["blocks_par"] = [[[Qi]] for Qi in range(self.n)]
        return out


class HData:
    """Family H (Hecke Y-gauge): S̄, mixed S with explicit (X,a,b)/(Q,a,b)
    labels -> multiplicity blocks."""

    def __init__(self, R, root=DATA_DIR, family="H"):
        with gzip.open(os.path.join(root, "%s_%s.json.gz" % (family, "".join(map(str, R)))), "rt") as f:
            d = json.load(f)
        self.R = tuple(R)
        self.family = family
        self.anti, self.par = d["anti"], d["par"]
        self.mats = {k: [[(_Poly(n), _Poly(dd)) for n, dd in row] for row in d[k]]
                     for k in ("Sbar", "S") if k in d}
        self.Tpar = d["T"]
        self.n = len(self.anti)
        self.blocks_anti = self._blocks([((tuple(x["Z"]), tuple(x["Zp"])), x["a"], x["b"])
                                         for x in self.anti])
        self.blocks_par = self._blocks([(tuple(x["Q"]), x["a"], x["b"]) for x in self.par])
        self.vac = next(i for i, x in enumerate(self.anti) if not x["Z"] and not x["Zp"])
        self.flat = {k: _Flat(M) for k, M in self.mats.items()}

    def evaluate_np(self, p, A, q):
        import numpy as np
        from ..reps.partitions import kappa
        from .interpolation import Point
        F = GF(p)
        pw = _powers(p, A, q)
        S = self.flat["S"].evaluate(p, pw, q)
        Sinv = _inv_np(S, p)
        FA, Fq = F(A), F(q)
        theta = FA ** sum(self.R) * Fq ** (2 * kappa(self.R))
        T = np.array([int(sg * FA ** ea * Fq ** eq / theta) for sg, ea, eq in self.Tpar], dtype=np.int64)
        Tb = np.array([int(x["eps"] * FA ** sum(x["Z"]) * Fq ** (kappa(tuple(x["Z"])) + kappa(tuple(x["Zp"]))))
                       for x in self.anti], dtype=np.int64)
        if self.family == "G":
            K = _mm_np(Sinv, T[:, None] * S % p, p)
            Sb = Tb[:, None] * K % p * Tb[None, :] % p
        else:
            Sb = self.flat["Sbar"].evaluate(p, pw, q)
        pt = Point(F, FA, Fq)
        d_anti = np.zeros(self.n, dtype=np.int64)
        for (Z, Zp), idx in self.blocks_anti:
            d_anti[[i for row in idx for i in row]] = int(pt.chi((), Z, Zp))
        d_par = np.zeros(self.n, dtype=np.int64)
        for Q, idx in self.blocks_par:
            d_par[[i for row in idx for i in row]] = int(qdim(Q, FA, Fq))
        return {"Sbar": Sb, "V": S, "S": Sinv, "T": T, "Tbar": Tb, "dR": int(qdim(self.R, FA, Fq)),
                "d_anti": d_anti, "d_par": d_par,
                "blocks_anti": [idx for _, idx in self.blocks_anti],
                "blocks_par": [idx for _, idx in self.blocks_par], "vac": self.vac}

    @staticmethod
    def _blocks(labels):
        groups = {}
        for i, (key, a, b) in enumerate(labels):
            groups.setdefault(key, []).append((a, b, i))
        out = []
        for key, items in groups.items():
            As = sorted({a for a, _, _ in items})
            Bs = sorted({b for _, b, _ in items})
            pos = {(a, b): i for a, b, i in items}
            out.append((key, [[pos[(a, b)] for b in Bs] for a in As]))
        return out

    def evaluate(self, F, A, q):
        from ..reps.partitions import kappa
        from .interpolation import Point
        cache = {}

        def ev(e):
            den = e[1].ev(F, A, q, cache)
            if den == 0:
                raise BadPoint("pole in Racah data")
            return e[0].ev(F, A, q, cache) / den
        S = [[ev(e) for e in row] for row in self.mats["S"]]
        Sb = [[ev(e) for e in row] for row in self.mats["Sbar"]] if "Sbar" in self.mats else None
        Sinv = _inv(S, F)
        dR = qdim(self.R, A, q)
        theta = A ** sum(self.R) * q ** (2 * kappa(self.R))
        T = [sg * A ** ea * q ** eq / theta for sg, ea, eq in self.Tpar]
        Tb = [x["eps"] * A ** sum(x["Z"]) * q ** (kappa(tuple(x["Z"])) + kappa(tuple(x["Zp"])))
              for x in self.anti]
        if self.family == "G":
            # family H satisfies T̄^-1 S̄ T̄^-1 = S^-1 T S; family G publishes S̄
            # in a vacuum-dual gauge (rows and columns normalised differently),
            # so S̄ is rebuilt from this identity in the gauge of S's columns
            K = _mm(Sinv, [[T[i] * S[i][j] for j in range(len(S))] for i in range(len(S))], F)
            Sb = [[Tb[i] * K[i][j] * Tb[j] for j in range(len(S))] for i in range(len(S))]
        pt = Point(F, A, q)
        d_anti = [F.zero] * self.n
        for (Z, Zp), idx in self.blocks_anti:
            dX = pt.chi((), Z, Zp)
            for row in idx:
                for i in row:
                    d_anti[i] = dX
        d_par = [F.zero] * self.n
        for Q, idx in self.blocks_par:
            dQ = qdim(Q, A, q)
            for row in idx:
                for i in row:
                    d_par[i] = dQ
        # engine slots: V = (par,anti) transform c_Hpar = V v_Vanti ; S = (anti,par)
        return {"Sbar": Sb, "V": S, "S": Sinv, "T": T, "Tbar": Tb, "dR": dR,
                "d_anti": d_anti, "d_par": d_par,
                "blocks_anti": [idx for _, idx in self.blocks_anti],
                "blocks_par": [idx for _, idx in self.blocks_par], "vac": self.vac}


@lru_cache(maxsize=None)
def load(R, root=DATA_DIR):
    R = tuple(R)
    key = "".join(map(str, R))
    if os.path.exists(os.path.join(root, "P_%s.json.gz" % key)):
        return PData(R, root)
    if os.path.exists(os.path.join(root, "H_%s.json.gz" % key)):
        return HData(R, root, "H")
    return HData(R, root, "G")


@lru_cache(maxsize=None)
def available(root=DATA_DIR):
    if not os.path.isdir(root):
        return []
    return sorted({tuple(int(c) for c in f[2:-8]) for f in os.listdir(root)
                   if f[:2] in ("P_", "H_", "G_") and f.endswith(".json.gz")})


# ---------------------------------------------------------------------------
# small dense linear algebra over F
# ---------------------------------------------------------------------------

def _mv(M, v, F):
    return [sum((M[i][j] * v[j] for j in range(len(v))), F.zero) for i in range(len(M))]


def _inv(M, F):
    from ..algebra.linalg import inverse
    return inverse(M, F.one)


def _mm(X, Y, F):
    return [[sum((X[i][k] * Y[k][j] for k in range(len(Y))), F.zero) for j in range(len(Y[0]))]
            for i in range(len(X))]


NP_BOUND = 2 ** 21       # float64 BLAS products are exact for p < 2^21, n < 2048


def _mm_np(X, Y, p):
    import numpy as np
    return np.fmod(X.astype(np.float64) @ Y.astype(np.float64), p).astype(np.int64)


def _inv_np(M, p):
    from .two_bridge import _inv_mod_np
    try:
        if M.shape[0] > 48:
            # M^-1 = G (M G)^-1 with a random G: M G has nonsingular leading
            # blocks with high probability even when M is sparse/structured
            import numpy as np
            G = np.random.default_rng(M.shape[0]).integers(0, p, M.shape)
            try:
                return _mm_np(G, _inv_blocked(_mm_np(M, G, p), p), p)
            except BadPoint:          # unlucky: pivoted elimination
                pass
        return _inv_mod_np(M, p)
    except BadPoint:
        raise BadPoint("singular Racah block")


def _inv_blocked(M, p):
    """Inverse by 2x2 Schur complements, products via exact float64 BLAS."""
    from .two_bridge import _inv_mod_np
    import numpy as np
    n = M.shape[0]
    if n <= 48:
        return _inv_mod_np(M, p)
    k = n // 2
    A, B, C, D = M[:k, :k], M[:k, k:], M[k:, :k], M[k:, k:]
    Ai = _inv_blocked(A, p)
    AiB, CAi = _mm_np(Ai, B, p), _mm_np(C, Ai, p)
    Si = _inv_blocked((D - _mm_np(C, AiB, p)) % p, p)
    X = _mm_np(AiB, Si, p)
    Y = _mm_np(Si, CAi, p)
    return np.block([[(Ai + _mm_np(X, CAi, p)) % p, (-X) % p], [(-Y) % p, Si]])


def natural_value_np(fracs, D, p):
    """``natural_value`` with numpy arrays mod p < NP_BOUND."""
    import numpy as np
    comps, tl = _orientations(tuple(Fraction(x) for x in fracs))
    if comps != 1:
        raise ValueError("Montesinos sum is not a knot")
    M = {("anti", "anti"): D["Sbar"], ("par", "anti"): D["V"], ("anti", "par"): D["S"]}
    Minv = {("par", "anti"): D["S"], ("anti", "par"): D["V"]}
    n = D["Sbar"].shape[0]
    tb, tp = D["Tbar"], D["T"]
    tbi = np.array([pow(int(x), -1, p) for x in tb], dtype=np.int64)
    tpi = np.array([pow(int(x), -1, p) for x in tp], dtype=np.int64)

    def pw(ev, evi, e):
        base = ev if e > 0 else evi
        out = np.ones(n, dtype=np.int64)
        for _ in range(abs(e)):
            out = out * base % p
        return out
    vecs, verts = [], []
    for base, ops, steps in tl:
        basis = "V" if base == "0" else "H"
        v = np.zeros(n, dtype=np.int64)
        v[D["vac"]] = 1
        for (kind, s), o in zip(ops, steps[:-1]):
            h, vv = _types(o)
            if kind == "H":
                if basis == "V":
                    v, basis = _mm_np(M[(h, vv)], v[:, None], p)[:, 0], "H"
                ev, evi, e = (tb, tbi, s * GROUP) if h == "anti" else (tp, tpi, -s)
            else:
                if basis == "H":
                    key = (h, vv)
                    if key not in Minv:
                        Minv[key] = _inv_np(M[key], p)
                    v, basis = _mm_np(Minv[key], v[:, None], p)[:, 0], "V"
                ev, evi, e = (tb, tbi, s) if vv == "anti" else (tp, tpi, -s * GROUP)
            v = v * pw(ev, evi, e) % p
        if basis == "V":
            v = _mm_np(M[_types(steps[-1])], v[:, None], p)[:, 0]
        vecs.append(v)
        verts.append(_types(steps[-1])[0])
    vert = verts[0]
    E = (D["Sbar"] if vert == "anti" else D["V"])[:, D["vac"]]
    dims = D["d_anti"] if vert == "anti" else D["d_par"]
    blocks = D["blocks_anti"] if vert == "anti" else D["blocks_par"]
    tot = 0
    by_shape = {}
    for idx in blocks:
        by_shape.setdefault((len(idx), len(idx[0])), []).append(idx)
    for idxs in by_shape.values():         # all blocks of one shape at once
        ix = np.array(idxs)
        Ei = _inv_stack(E[ix], p)
        prod = None
        for v in vecs:
            X = _mm_np(v[ix], Ei, p)
            prod = X if prod is None else _mm_np(prod, X, p)
        tr = np.trace(prod, axis1=1, axis2=2) % p
        tot = (tot + int((dims[ix[:, 0, 0]] * tr % p).sum() % p)) % p
    return tot * pow(int(D["dR"]), -1, p) % p


def _inv_stack(M, p):
    """Inverses of a stack of small matrices (Gauss--Jordan, vectorised over
    the stack; a zero pivot falls back to pivoted elimination per matrix)."""
    import numpy as np
    m, n, _ = M.shape
    X = np.concatenate([M % p, np.broadcast_to(np.eye(n, dtype=np.int64), (m, n, n))], axis=2)
    for c in range(n):
        piv = X[:, c, c]
        if not piv.all():
            return np.array([_inv_np(B, p) for B in M])
        X[:, c] = X[:, c] * _inv_vec(piv, p)[:, None] % p
        f = X[:, :, c].copy()
        f[:, c] = 0
        X = (X - f[:, :, None] * X[:, c][:, None, :]) % p
    return X[:, :, n:]


# ---------------------------------------------------------------------------
# engine
# ---------------------------------------------------------------------------

def _transforms(D, F):
    M = {("anti", "anti"): D["Sbar"], ("par", "anti"): D["V"], ("anti", "par"): D["S"]}
    return M, {k: _inv(m, F) for k, m in M.items()}


def natural_value(fracs, D, F):
    """Reduced invariant of N(T_1 + ... + T_k) from evaluated data D (dict)."""
    comps, tl = _orientations(tuple(Fraction(x) for x in fracs))
    if comps != 1:
        raise ValueError("Montesinos sum is not a knot")
    M, Minv = _transforms(D, F)
    n = len(D["Sbar"])
    e0 = [F.zero] * n
    e0[D.get("vac", 0)] = F.one
    tb, tp = D["Tbar"], D["T"]
    vecs, verts = [], []
    for base, ops, steps in tl:
        basis = "V" if base == "0" else "H"
        v = list(e0)
        for (kind, s), o in zip(ops, steps[:-1]):
            h, vv = _types(o)
            if kind == "H":
                if basis == "V":
                    v, basis = _mv(M[(h, vv)], v, F), "H"
                ev, e = (tb, s * GROUP) if h == "anti" else (tp, -s)
            else:
                if basis == "H":
                    v, basis = _mv(Minv[(h, vv)], v, F), "V"
                ev, e = (tb, s) if vv == "anti" else (tp, -s * GROUP)
            v = [x * y ** e for x, y in zip(v, ev)]
        if basis == "V":
            v = _mv(M[_types(steps[-1])], v, F)
        vecs.append(v)
        verts.append(_types(steps[-1])[0])
    vert = verts[0]
    E = _mv(M[("anti", "anti")] if vert == "anti" else M[("par", "anti")], e0, F)
    dims = D["d_anti"] if vert == "anti" else D["d_par"]
    blocks = D["blocks_anti"] if vert == "anti" else D["blocks_par"]
    tot = F.zero
    for idx in blocks:
        m = len(idx)
        Em = [[E[idx[i][j]] for j in range(m)] for i in range(m)]
        Ei = _inv(Em, F)
        prod = None
        for v in vecs:
            Cm = [[v[idx[i][j]] for j in range(m)] for i in range(m)]
            X = _mm(Cm, Ei, F)
            prod = X if prod is None else _mm(prod, X, F)
        tr = sum((prod[i][i] for i in range(m)), F.zero)
        tot = tot + dims[idx[0][0]] * tr
    return tot / D["dR"]


def value(fracs, R, F, A, q, root=DATA_DIR):
    """H_R of N(sum of tangles) at (A, q); with the sign of the fractions fixed
    by ``chirality`` this is the STANDARD convention.  A representation without
    data is taken from its transpose, H_{R^T}(A, q) = H_R(A, -1/q)."""
    R = P(R)
    if R not in available(root) and conjugate(R) in available(root):
        R, q = conjugate(R), -1 / q
    d = load(R, root)
    p = getattr(F, "p", None)
    if p is not None and p < NP_BOUND:
        return F(natural_value_np(fracs, d.evaluate_np(p, int(A), int(q)), p))
    return natural_value(fracs, d.evaluate(F, A, q), F)


def chirality(fracs, reference, braid=None):
    """Sign s such that N(s*fractions) matches ``reference`` (the STANDARD
    fundamental HOMFLY).  If H_[1] is mirror-symmetric and a braid of the knot
    is given, the tie is broken with H_[2] by cabling (2 x strands <= 9);
    otherwise None."""
    F = GF(2 ** 61 - 1)
    rng = random.Random(hash(tuple(fracs)) & 0xffff)
    A, q = F.random_element(rng), F.random_element(rng)
    ref = reference.evaluate([A, q], one=F.one)
    hits = [s for s in (1, -1) if value([s * Fraction(x) for x in fracs], (1,), F, A, q) == ref]
    if not hits:
        raise ValueError("no chirality matches the reference")
    if len(hits) == 1:
        return hits[0]
    if braid is None or 2 * braid.strands > 9:
        return None
    from ..algebra.fields import primes_below
    from .cabling import Cabling
    F = GF(primes_below(2 ** 21, 1)[0])
    A, q = F.random_element(rng), F.random_element(rng)
    ref2 = Cabling(max_strands=9).evaluate(braid, (2,), F, A, q)
    hits = [s for s in (1, -1) if value([s * Fraction(x) for x in fracs], (2,), F, A, q) == ref2]
    return hits[0] if len(hits) == 1 else None


class MontesinosMethod(Method):
    name = "montesinos"
    prime_bound = NP_BOUND        # numpy/BLAS fast path

    def __init__(self, root=DATA_DIR):
        self.root = root

    def supports(self, knot, R):
        av = available(self.root)
        return isinstance(knot, MontesinosKnot) and (P(R) in av or conjugate(P(R)) in av)

    def evaluate(self, knot, R, F, A, q):
        return value(knot.fractions(), R, F, A, q, self.root)
